export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const SET_LOADER = "SET_LOADER";
export const GET_INDIVIDUAL_COINS = "GET_INDIVIDUAL_COINS";
export const CLEAR_COINS = "CLEAR_COINS";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
export const EDIT_IN_ORACLE = "EDIT_IN_ORACLE";
export const CHNAGE_NETWORK = "CHNAGE_NETWORK";

/** Admin Setting Constants */
export const SET_MIN_XIV_STAKE_AMOUNT = "SET_MIN_XIV_STAKE_AMOUNT";
export const GET_MINIMUM_STAKE_AMOUNT = "GET_MINIMUM_STAKE_AMOUNT";
